# Render Blueprint for DentWizard
# Frontend only - API runs on AWS EC2

services:
  # React Frontend - Production
  - type: web
    name: dentwizard-app
    runtime: static
    repo: https://github.com/infonetproducts/dentwizard
    branch: main
    buildCommand: cd react-app && npm install && REACT_APP_API_URL=$REACT_APP_API_URL npm run build
    staticPublishPath: ./react-app/build
    envVars:
      - key: REACT_APP_API_URL
        sync: false  # Set manually in Render dashboard - your AWS EC2 API URL
      - key: REACT_APP_ENVIRONMENT
        value: production
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    headers:
      - path: /*
        name: X-Frame-Options
        value: SAMEORIGIN
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
